### ISSUE TITLE
请问这个有实例代码嘛？

### ISSUE THREAD

**Issue by PhilCuriosity** [RapidOCR/paddle2onnx-wild#2]
我尝试着通过paddle2onnx/command.py文件将自训练的PPOCR转为ONNX, 主要是向解决ONNX2TRT缺少scatterND算子的问题
https://github.com/PaddlePaddle/Paddle2ONNX/issues/212

**Comment by benjaminwan** [comment]
手动转换说明参考：
https://github.com/RapidOCR/RapidOCR/tree/main/models

根据上面的说明做的自动转换仓库
https://github.com/RapidOCR/Paddle2OnnxConvertor
这个是核心的转换脚本
https://github.com/RapidOCR/Paddle2OnnxConvertor/blob/main/convert-models.sh

**Comment by PhilCuriosity** [comment]
> 手动转换说明参考：
> https://github.com/RapidOCR/RapidOCR/tree/main/models
> 
> 根据上面的说明做的自动转换仓库
> https://github.com/RapidOCR/Paddle2OnnxConvertor
> 这个是核心的转换脚本
> https://github.com/RapidOCR/Paddle2OnnxConvertor/blob/main/convert-models.sh

好的，谢谢。我通过升级paddle2onnx解决这个问题。再次感谢！
